package WebProgramming;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private final static Logger logger = LoggerFactory.getLogger(App.class);
    
    public static void main(String[] args) throws SQLException {
        // SampleWebServer is the heart of the application
        SampleWebServer sampleWebServer = new SampleWebServer("src\\main\\resources");
        sampleWebServer.init();

        // HyperSQL SQL database example (in memory) - not used by SampleWebServer, but may be useful for group project
        Connection c = DriverManager.getConnection("jdbc:hsqldb:mem:appdb", "sa", "");
        Statement s = c.createStatement();
        System.err.println(s.execute("CREATE TABLE users (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(32), password VARCHAR(32), fullname VARCHAR(64));"));
        System.err.println(s.executeUpdate("INSERT INTO users (username, password, fullname) VALUES('admin', 'Jumanji', 'Administrator')"));
        System.err.println(s.executeUpdate("INSERT INTO users (username, password, fullname) VALUES('tom', 'mysecret', 'Tom Smith')"));
        System.err.println(s.executeUpdate("INSERT INTO users (username, password, fullname) VALUES('dave', 'dave', 'Dave<script>alert(\"Hello Dave\");</script>')"));
    }
}
